version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pg-db
    restart: unless-stopped
    ports: [":5432"]
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB} || pg_isready -U ${PG_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pg-admin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports: [":80"]
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin-data:
