services:
  db:
    image: postgres:16
    container_name: pg-db
    restart: unless-stopped
    ports:
      - "${PG_PORT}:5432"         
    environment:
      POSTGRES_PASSWORD: postgres 
      TZ: "UTC"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pg-admin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
