name: CI
on:
  pull_request:
    branches: [ develop, main ]
jobs:
  test-moderation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install -U pip pytest
      - run: pytest -q moderation
